/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControlCalificacionesEstudiante;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Curso;
import modelo.DetalleNota;
import modelo.Estudiante;
import modelo.Nota;

/**
 *
 * @author JORGE
 */
public class PanelCalificacionesEstudiante extends javax.swing.JFrame {
        ControlCalificacionesEstudiante controlCE;
        ArrayList<Curso> cursos;
        ArrayList<Nota> notas;
        ArrayList<DetalleNota> detalles;
        Estudiante estudiante;
        int idCurso;
      
    /**
     * Creates new form PanelCalificacionesEstudiante
     */
    public PanelCalificacionesEstudiante(Estudiante estudiante, int idCurso) {
        initComponents();
        setLocationRelativeTo(this);
        this.estudiante = estudiante;
        this.idCurso = idCurso;
        controlCE = new ControlCalificacionesEstudiante();
        cursos = controlCE.conseguirCursosEstudiante(estudiante);
        notas = controlCE.notasCurso(idCurso, cursos);
        detalles = consegirDetalle(estudiante);
        llenarTablaRazon();
        llenarTablaDetalle();
        lblNotaAcomulada.setText("Nota acomulada: " + notaAcomulada());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRazon = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        lblNotaAcomulada = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalles = new javax.swing.JTable();
        lblFOndo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaRazon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Razon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaRazon);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 200));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 351, -1, -1));

        lblNotaAcomulada.setText("Nota acomulada: ");
        getContentPane().add(lblNotaAcomulada, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 150, 20));

        tablaDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaDetalles);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 0, 260, 200));

        lblFOndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondo.png"))); // NOI18N
        getContentPane().add(lblFOndo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 510, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        PanelCursosRegistradosE panelCR = new PanelCursosRegistradosE(estudiante);
        panelCR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
       
    public void llenarTablaRazon(){
    DefaultTableModel modelo = new DefaultTableModel(new String[]{"Razon"},notas.size());
    tablaRazon.setModel(modelo);
    TableModel modeloRazon = tablaRazon.getModel();
        for (int i = 0; i < notas.size(); i++) {
            Nota nota = notas.get(i);
            modeloRazon.setValueAt(nota.getRazon(), i, 0);
        }
    }
    
    public void llenarTablaDetalle(){
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Nota"},detalles.size());
        tablaDetalles.setModel(modelo);
        TableModel modeloDetalle = tablaDetalles.getModel();
        for (int i = 0; i < detalles.size(); i++) {
            DetalleNota detalle = detalles.get(i);
            modeloDetalle.setValueAt(detalle.getNota(), i, 0);
        }
    }
    
    public ArrayList<DetalleNota> consegirDetalle(Estudiante estudiante){
        ArrayList<DetalleNota> detalles = new ArrayList<>();
        for (Nota nota : notas) {
            for (DetalleNota detalle : nota.getDetalles()) {
                if(detalle.getEstudiante().getNombre().equals(estudiante.getNombre())){
                    detalles.add(detalle);
                }
            }
        }
        return detalles;
    }
    
    public float notaAcomulada(){
        float notaAcumulada = 0;
        for (DetalleNota detalleNota : detalles) {
            notaAcumulada = notaAcumulada + detalleNota.getNota();
        }
        return notaAcumulada/detalles.size();
    }
   
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFOndo;
    private javax.swing.JLabel lblNotaAcomulada;
    private javax.swing.JTable tablaDetalles;
    private javax.swing.JTable tablaRazon;
    // End of variables declaration//GEN-END:variables
}
