/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControlPanelHacerReserva;
import excepciones.NoTieneReserva;
import excepciones.ReservaActiva;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Estudiante;
import modelo.Horario;
import modelo.Laboratorio;
import modelo.Reserva;

/**
 *
 * @author JORGE
 */
public class PanelHacerReserva extends javax.swing.JFrame {
    ControlPanelHacerReserva controlPHR;
    Estudiante estudiante;
    
    /**
     * Creates new form HacerReserva
     */
    public PanelHacerReserva(Estudiante estudiante) {
        initComponents();
        setLocationRelativeTo(this);
        this.estudiante = estudiante;
        controlPHR = new ControlPanelHacerReserva();
        
        llenarComboBox();
        cbLabs.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        dateReserva = new com.toedter.calendar.JDateChooser();
        lblFechaReserva = new javax.swing.JLabel();
        cbLabs = new javax.swing.JComboBox<>();
        lblLaboratorios = new javax.swing.JLabel();
        lblTtulo = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JTextField();
        txtHoraFinal = new javax.swing.JTextField();
        lblHoraInicio = new javax.swing.JLabel();
        lblHoraFinal = new javax.swing.JLabel();
        btnCacelarReserva = new javax.swing.JButton();
        btnHacerReserva = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 351, -1, -1));
        getContentPane().add(dateReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 100, -1));

        lblFechaReserva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaReserva.setText("Fecha:");
        getContentPane().add(lblFechaReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 90, -1, -1));

        getContentPane().add(cbLabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 128, 100, -1));

        lblLaboratorios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLaboratorios.setText("Labs:");
        getContentPane().add(lblLaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 128, -1, -1));

        lblTtulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTtulo.setText("Hacer reservas");
        getContentPane().add(lblTtulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 132, -1));
        getContentPane().add(txtHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 100, -1));
        getContentPane().add(txtHoraFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 100, -1));

        lblHoraInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHoraInicio.setText("Hora inicio:");
        getContentPane().add(lblHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        lblHoraFinal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHoraFinal.setText("Hora final:");
        getContentPane().add(lblHoraFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        btnCacelarReserva.setText("Cancelar reserva");
        btnCacelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCacelarReservaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCacelarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 120, -1));

        btnHacerReserva.setText("Generar reserva");
        btnHacerReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHacerReservaActionPerformed(evt);
            }
        });
        getContentPane().add(btnHacerReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 120, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 500, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaUsEstudiante ventanaUE = new VentanaUsEstudiante(estudiante);
        ventanaUE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnHacerReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHacerReservaActionPerformed
        // TODO add your handling code here:
        try{
        LocalDate fechaReserva = dateReserva.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        System.out.println("fecha " + fechaReserva);
        int idLaboratorio = Integer.parseInt(String.valueOf(cbLabs.getSelectedItem()));
        
       
        LocalTime horaInicio = LocalTime.parse(txtHoraInicio.getText());
        LocalTime horaFinal = LocalTime.parse(txtHoraFinal.getText());
        
        Reserva reserva = new Reserva(fechaReserva, idLaboratorio,horaInicio, horaFinal);
        
//        estudiante.setReserva(reserva);
//        estudiante.setTieneReserva(true);
        controlPHR.generarReserva(idLaboratorio, reserva, estudiante.getId());
        limpiarCampos();
        }catch(ReservaActiva ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
            limpiarCampos();
        }
    }//GEN-LAST:event_btnHacerReservaActionPerformed

    private void btnCacelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCacelarReservaActionPerformed
        // TODO add your handling code here:
        try{
         controlPHR.cancelarReserva(estudiante.getId());
        
        }catch(NoTieneReserva ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnCacelarReservaActionPerformed

    public void llenarComboBox(){
        ArrayList<Laboratorio> labs = controlPHR.getLabs();
        DefaultComboBoxModel<String> modeloLabs = new DefaultComboBoxModel<>();
        for (Laboratorio lab : labs) {
            modeloLabs.addElement(String.valueOf(lab.getIdLaboratorio()));
        }
        cbLabs.setModel(modeloLabs);
    }
    public void limpiarCampos(){
        dateReserva.setDate(null);
        cbLabs.setSelectedItem(null);
        txtHoraInicio.setText("");
        txtHoraFinal.setText("");
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCacelarReserva;
    private javax.swing.JButton btnHacerReserva;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbLabs;
    private com.toedter.calendar.JDateChooser dateReserva;
    private javax.swing.JLabel lblFechaReserva;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHoraFinal;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblLaboratorios;
    private javax.swing.JLabel lblTtulo;
    private javax.swing.JTextField txtHoraFinal;
    private javax.swing.JTextField txtHoraInicio;
    // End of variables declaration//GEN-END:variables
}
