/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.util.Calendar;
import modelo.Administrativo;

/**
 *
 * @author JORGE
 */
public class VentanaUsAdministrativo extends javax.swing.JFrame {

    Administrativo administrativo;

    /**
     * Creates new form VentanaUsAdministrativo
     */
    public VentanaUsAdministrativo(Administrativo administrativo) {
        initComponents();
        setLocationRelativeTo(this);
        this.administrativo = administrativo;
        informacionAdministrativo(administrativo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSecion = new javax.swing.JButton();
        lblAdministrativo = new javax.swing.JLabel();
        LblBirthDate = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblEdadAdmin = new javax.swing.JLabel();
        lblBirthDateAdmin = new javax.swing.JLabel();
        lblNombreAdministrativo = new javax.swing.JLabel();
        lblInformacionDeUsuario = new javax.swing.JLabel();
        LblLineaLimite = new javax.swing.JLabel();
        btnCrearCursos = new javax.swing.JButton();
        btnGestionmPersonal = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSecion.setText("Cerrar secion");
        btnCerrarSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSecionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 471, -1, -1));

        lblAdministrativo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAdministrativo.setText("Administrativo:");
        getContentPane().add(lblAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, -1, -1));

        LblBirthDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblBirthDate.setText("Año de nacimiento:");
        getContentPane().add(LblBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, -1, -1));

        lblEdad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEdad.setText("Edad:");
        getContentPane().add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 86, -1, -1));
        getContentPane().add(lblEdadAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 86, 109, 20));
        getContentPane().add(lblBirthDateAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 60, 109, 20));
        getContentPane().add(lblNombreAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 34, 110, 20));

        lblInformacionDeUsuario.setText("Informacion de usuario------------------------------------------------------------");
        getContentPane().add(lblInformacionDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        LblLineaLimite.setText("________________________________________________________________________________________");
        getContentPane().add(LblLineaLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 112, 441, -1));

        btnCrearCursos.setText("Crear curso");
        btnCrearCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCursosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 251, -1));

        btnGestionmPersonal.setText("Gestion del personal");
        btnGestionmPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionmPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestionmPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 250, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondo2.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 460, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSecionActionPerformed
        // TODO add your handling code here:
        PanelPrincipal panelP = new PanelPrincipal();
        panelP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSecionActionPerformed

    private void btnCrearCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCursosActionPerformed
        // TODO add your handling code here:
        VentanaCursos ventanaC = new VentanaCursos(administrativo);
        ventanaC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearCursosActionPerformed

    private void btnGestionmPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionmPersonalActionPerformed
        // TODO add your handling code here:
        PanelAdministrador panelA = new PanelAdministrador();
        panelA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionmPersonalActionPerformed
    public void informacionAdministrativo(Administrativo admin) {
        Administrativo aux = admin;
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(aux.getBirthDate());
        lblNombreAdministrativo.setText(aux.getNombre());
        lblBirthDateAdmin.setText(String.valueOf(calendar.get(Calendar.YEAR)));
        lblEdadAdmin.setText(String.valueOf(2024 - calendar.get(Calendar.YEAR)));

    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblBirthDate;
    private javax.swing.JLabel LblLineaLimite;
    private javax.swing.JButton btnCerrarSecion;
    private javax.swing.JButton btnCrearCursos;
    private javax.swing.JButton btnGestionmPersonal;
    private javax.swing.JLabel lblAdministrativo;
    private javax.swing.JLabel lblBirthDateAdmin;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEdadAdmin;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblInformacionDeUsuario;
    private javax.swing.JLabel lblNombreAdministrativo;
    // End of variables declaration//GEN-END:variables
}
