/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControlPanelCambiarContraseña;
import controladores.ControladorPrincipal;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author JORGE
 */
public class panelCambiarContraseña extends javax.swing.JFrame {

    Usuario usuario;
    ControlPanelCambiarContraseña controlPCC;

    /**
     * Creates new form panelCambiarContraseña
     */
    public panelCambiarContraseña() {
        initComponents();
        setLocationRelativeTo(this);
        usuario = new Usuario("", 0, "");
        controlPCC = new ControlPanelCambiarContraseña();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNuevaContraseña = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        btnCambiar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNuevaContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNuevaContraseña.setText("Ingrese su nueva contraseña");
        getContentPane().add(lblNuevaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, 26));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 99, 104, -1));

        btnCambiar.setText("Cambiar");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 133, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -20, 450, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        // TODO add your handling code here:}
        String nuevaContraseña = txtContraseña.getText();
        if (!usuario.getContraseña().equals(nuevaContraseña)) {
            controlPCC.validarNuevaContraseña(usuario.getNombre(), usuario.getContraseña(), nuevaContraseña);
            PanelPrincipal panelP = new PanelPrincipal();
            panelP.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "No puede ser \n la misma contraseña");
        }
    }//GEN-LAST:event_btnCambiarActionPerformed
    public void cambiarContraseña(Usuario aux) {
        this.usuario = aux;
        
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNuevaContraseña;
    private javax.swing.JTextField txtContraseña;
    // End of variables declaration//GEN-END:variables
}
