/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControlVentanaAgregarEstudiante;
import excepciones.EstudianteNoEliminado;
import excepciones.EstudianteNoInscrito;
import excepciones.IdIncorrecto;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Administrativo;
import modelo.Curso;
import modelo.Estudiante;

/**
 *
 * @author JORGE
 */
public class VentanaAgregarEstudiantes extends javax.swing.JFrame {

    ControlVentanaAgregarEstudiante controlVAE;
    Administrativo administrativo;
    int idCurso;
    Curso curso;

    /**
     * Creates new form VentanaAgregarEstudiantes
     */
    public VentanaAgregarEstudiantes(Administrativo administrativo, int idCurso) throws IdIncorrecto {
        initComponents();
        setLocationRelativeTo(this);
        this.administrativo = administrativo;
        controlVAE = new ControlVentanaAgregarEstudiante();
        this.idCurso = idCurso;
        this.curso = controlVAE.conseguirCurso(idCurso);
        if(controlVAE.conseguirCurso(idCurso) == null){
        throw new IdIncorrecto();
        }
        lblCurso.setText("Curso № " + curso.getId());
        lblDocenteCurso.setText(curso.getDocente().getNombre());
        llenarComboBoxEstudiante();
        llenarTablaEstudiante();
        if (curso.getHorarios().isEmpty()) {
            btnInscribirEstudiante.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboEstudiantes = new javax.swing.JComboBox<>();
        lblIdEstudiantes = new javax.swing.JLabel();
        btnInscribirEstudiante = new javax.swing.JButton();
        btnEliminarEstudiante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        lblCurso = new javax.swing.JLabel();
        lblDocenteCurso = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(jComboEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 108, 100, -1));

        lblIdEstudiantes.setText("Id estudiante:");
        getContentPane().add(lblIdEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 111, -1, -1));

        btnInscribirEstudiante.setText("Inscribir");
        btnInscribirEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(btnInscribirEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 136, -1, -1));

        btnEliminarEstudiante.setText("Eliminar");
        btnEliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 136, -1, -1));

        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Id", "Programa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEstudiantes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 0, -1, 275));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 321, -1, -1));

        lblCurso.setText("Curso №");
        getContentPane().add(lblCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 26, 118, -1));

        lblDocenteCurso.setText("Docente:");
        getContentPane().add(lblDocenteCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 26, 119, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoAgregarHorarios.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscribirEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirEstudianteActionPerformed
        try {
            int indexE = jComboEstudiantes.getSelectedIndex();
            if (controlVAE.validarHorariosEstudiante(indexE, idCurso)) {
                controlVAE.inscribirEstudiante(indexE, curso.getId());
                llenarTablaEstudiante();
            } else {
                JOptionPane.showMessageDialog(null, "Imposible inscribir \n se crusan los horarios");
            }
        } catch (EstudianteNoInscrito ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnInscribirEstudianteActionPerformed

    private void btnEliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstudianteActionPerformed
        try {
            int indexE = jComboEstudiantes.getSelectedIndex();
            controlVAE.EliminarEstudiante(indexE, curso.getId());
            llenarTablaEstudiante();
        } catch (EstudianteNoEliminado ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarEstudianteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaCursos ventanaC = new VentanaCursos(administrativo);
        ventanaC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    public void llenarTablaEstudiante() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Nombre", "Id", "Programa"}, curso.getEstudiantes().size());
        tablaEstudiantes.setModel(modelo);
        TableModel modeloEstudiante = tablaEstudiantes.getModel();
        for (int i = 0; i < curso.getEstudiantes().size(); i++) {
            Estudiante estudiante = curso.getEstudiantes().get(i);
            modeloEstudiante.setValueAt(estudiante.getNombre(), i, 0);
            modeloEstudiante.setValueAt(estudiante.getId(), i, 1);
            modeloEstudiante.setValueAt(estudiante.getPrograma(), i, 2);
        }
    }

    public void llenarComboBoxEstudiante() {
        ArrayList<Estudiante> ests = controlVAE.listaUsuarioEsts();
        DefaultComboBoxModel<String> modeloEsts = new DefaultComboBoxModel<>();
        for (Estudiante estudiante : ests) {
            modeloEsts.addElement(estudiante.getNombre());
        }
        jComboEstudiantes.setModel(modeloEsts);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarEstudiante;
    private javax.swing.JButton btnInscribirEstudiante;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> jComboEstudiantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDocenteCurso;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIdEstudiantes;
    private javax.swing.JTable tablaEstudiantes;
    // End of variables declaration//GEN-END:variables
}
