/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControlVentanaLaboratorios;
import excepciones.LabNoEditado;
import excepciones.LabNoEleminado;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.AdminLab;
import modelo.Curso;
import modelo.Horario;
import modelo.Laboratorio;

/**
 *
 * @author JORGE
 */
public class VentanaLaboratorios extends javax.swing.JFrame {
    
    ControlVentanaLaboratorios controlVL;
    ArrayList<Curso> cursosLab;
     AdminLab adminLab;

    /**
     * Creates new form VentanaLaboratorios
     */
    public VentanaLaboratorios( AdminLab adminLab) {
        initComponents();
        setLocationRelativeTo(this);
        controlVL = new ControlVentanaLaboratorios();
        cursosLab = new ArrayList<>();
        this.adminLab = adminLab;
        txtIdLab.setText(controlVL.contadorIdLabs());
        llenarComboBoxDocentes();
        JComboCursos.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCrearCursos = new javax.swing.JLabel();
        lblIdCurso = new javax.swing.JLabel();
        lblNumeroPersonas = new javax.swing.JLabel();
        lblCursos = new javax.swing.JLabel();
        txtIdLab = new javax.swing.JTextField();
        txtNumeroPersonas = new javax.swing.JTextField();
        JComboCursos = new javax.swing.JComboBox<>();
        btnListaLabs = new javax.swing.JButton();
        btnCrearLab = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAñadirCursos = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCrearCursos.setText("Crear cursos------------------------------------------------------------------------------------");
        getContentPane().add(lblCrearCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        lblIdCurso.setText("Id:");
        getContentPane().add(lblIdCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        lblNumeroPersonas.setText("Numero de personas:");
        getContentPane().add(lblNumeroPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 132, -1, -1));

        lblCursos.setText("Cursos:");
        getContentPane().add(lblCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 172, -1, -1));
        getContentPane().add(txtIdLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 110, -1));
        getContentPane().add(txtNumeroPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 110, -1));

        JComboCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        JComboCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboCursosActionPerformed(evt);
            }
        });
        getContentPane().add(JComboCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 110, -1));

        btnListaLabs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Listar.png"))); // NOI18N
        btnListaLabs.setBorderPainted(false);
        btnListaLabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaLabsActionPerformed(evt);
            }
        });
        getContentPane().add(btnListaLabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 40, 50));

        btnCrearLab.setText("Validar Lab");
        btnCrearLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearLabActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 351, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        btnAñadirCursos.setText("Añadir");
        btnAñadirCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirCursosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAñadirCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 197, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, -1, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirCursosActionPerformed
        // TODO add your handling code here:
        int indiceCurso = JComboCursos.getSelectedIndex();
        if (cursosLab.contains(controlVL.getCursos().get(indiceCurso))) {
            JOptionPane.showMessageDialog(null, "Imposible inscribir\n esta incrito");
            JComboCursos.setSelectedItem(null);
/////////////////////////////////this is proob code///////////////////////////////////////// 
        } else if (verificarHorario(indiceCurso)) {
            JOptionPane.showMessageDialog(null, "Imposible inscribir\n Horario ocupado");
            JComboCursos.setSelectedItem(null);
        } else {
            cursosLab.add(controlVL.getCursos().get(indiceCurso));
            JOptionPane.showMessageDialog(null, "Curso inscrito");
            JComboCursos.setSelectedItem(null);
        }
    }//GEN-LAST:event_btnAñadirCursosActionPerformed

    private void btnCrearLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearLabActionPerformed
        // TODO add your handling code here:
        int idLaboratorios = Integer.parseInt(txtIdLab.getText());
        int numeroPersonas = Integer.parseInt(txtNumeroPersonas.getText());
        Laboratorio lab = new Laboratorio(idLaboratorios, numeroPersonas);
        
        lab.setCursos(cursosLab);
        lab.setHoras(integrarHorario());
        lab.setMantenimiento(false);
        boolean aux = controlVL.crearLaboratorio(lab);
        if (aux) {
            JOptionPane.showMessageDialog(null, "Agregado");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(null, "NO agrego");
            limpiarCampos();
        }
        

    }//GEN-LAST:event_btnCrearLabActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaUsAdminLab ventanaAL = new VentanaUsAdminLab(adminLab);
        ventanaAL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void JComboCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboCursosActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdLab.getText());
        Laboratorio lab = controlVL.buscarLaboratorio(id);
        if (lab != null) {
            txtIdLab.setText(String.valueOf(lab.getIdLaboratorio()));
            txtNumeroPersonas.setText(String.valueOf(lab.getNumeroPersonas()));
            
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListaLabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaLabsActionPerformed
        // TODO add your handling code here:
        VentanaListaLaborarotios ventanaLL = new VentanaListaLaborarotios(adminLab);
        ventanaLL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListaLabsActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            int idLaboratorios = Integer.parseInt(txtIdLab.getText());
            controlVL.eliminarLaboratorio(idLaboratorios);
        } catch (LabNoEleminado ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        try {
            int idLaboratorios = Integer.parseInt(txtIdLab.getText());
            int numeroPersonas = Integer.parseInt(txtNumeroPersonas.getText());
            controlVL.editarLaboratorio(idLaboratorios, numeroPersonas);
        } catch (LabNoEditado ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed
    
    public ArrayList<Horario> integrarHorario() {
        ArrayList<Horario> horario = new ArrayList<>();
        for (int i = 0; i < cursosLab.size(); i++) {
            horario.addAll(cursosLab.get(i).getHorarios());
        }
        return horario;
    }
    
    public void llenarComboBoxDocentes() {
        ArrayList<Curso> cursos = controlVL.getCursos();
        DefaultComboBoxModel<String> modeloCursos = new DefaultComboBoxModel<>();
        for (Curso curso : cursos) {
            modeloCursos.addElement(curso.getMateria());
        }
        JComboCursos.setModel(modeloCursos);
    }
    
    public void limpiarCampos() {
        txtIdLab.setText(controlVL.contadorIdLabs());
        txtNumeroPersonas.setText("");
        JComboCursos.setSelectedItem(null);
    }

    /**
     * tambien nesesita validar que si la hora de inicio del otro curso es igual
     * una mas que la hora de inicio del curso que ya esta en el lab y no se
     * puede inscribir pero si la hora de inicio del curso que se va a inscribir
     * es igual a la ora final del cuso anterior si si se puede inscribir
     *
     * @param indiceCurso
     * @return
     */
    public boolean verificarHorario(int indiceCurso) {
     ArrayList<Horario> horariosLab = horariosLaboratorio();
     ArrayList<Horario> horariosCurso = horariosCursoNuevo(indiceCurso);
        for (Horario horario :horariosLab) {
            for (Horario horario1 : horariosCurso) {
                if(horario1.getDia().equals(horario.getDia())){
                    if(horario1.getHoraInicio().isBefore(horario.getHoraFinal())
                            ||horario1.getHoraFinal().isBefore(horario.getHoraInicio())
                            ||horario1.getHoraInicio().equals(horario.getHoraFinal())
                            ||horario1.getHoraFinal().equals(horario.getHoraInicio())){
                        return true;
                    }
                }
            }
        }
        return false;
    }
    
    public ArrayList<Horario> horariosLaboratorio(){
        ArrayList<Horario> horariosLab = new ArrayList<>();
        for (int i = 0; i < cursosLab.size(); i++) {
            horariosLab.addAll(cursosLab.get(i).getHorarios());
        }
       return horariosLab;
    }
    public  ArrayList<Horario> horariosCursoNuevo(int indexCurso){
        ArrayList<Horario> horariosCurso = new ArrayList<>();
        horariosCurso.addAll(controlVL.getCursos().get(indexCurso).getHorarios());
        return horariosCurso;  
    }
    
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboCursos;
    private javax.swing.JButton btnAñadirCursos;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrearLab;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListaLabs;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblCrearCursos;
    private javax.swing.JLabel lblCursos;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIdCurso;
    private javax.swing.JLabel lblNumeroPersonas;
    private javax.swing.JTextField txtIdLab;
    private javax.swing.JTextField txtNumeroPersonas;
    // End of variables declaration//GEN-END:variables
}
