/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControlVentanaCursos;
import excepciones.CursoNoEncontrado;
import excepciones.CursoExistente;
import excepciones.CursoNoRemovido;
import excepciones.CursoSInHorarios;
import excepciones.HorarioNoAdmitido;
import excepciones.IdIncorrecto;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Administrativo;
import modelo.Curso;
import modelo.Docente;
import modelo.Estudiante;
import modelo.Horario;
import modelo.Notificacion;

/**
 *
 * @author JORGE
 */
public class VentanaCursos extends javax.swing.JFrame {

    ControlVentanaCursos controlVC;
    ArrayList<Estudiante> estsCurso;
    Administrativo administrativo;

    /**
     * Creates new form VentanaCursos
     */
    public VentanaCursos(Administrativo administrativo) {
        initComponents();
        setLocationRelativeTo(this);
        this.administrativo = administrativo;
        controlVC = new ControlVentanaCursos();
        estsCurso = new ArrayList<>();
        txtId.setText(controlVC.contadorIdCursos());
        llenarComboBoxDocentes();
        llenarTablaCursos();
        comboJornada.setSelectedItem(null);
        JComboDocentes.setSelectedItem(null);
        lblPeriodo2.setText(String.valueOf(controlVC.validacionPeriodo()));

    }

    public ArrayList<Estudiante> getEstsCurso() {
        return estsCurso;
    }

    public void setEstsCurso(ArrayList<Estudiante> estsCurso) {
        this.estsCurso = estsCurso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        lblCrearCursos = new javax.swing.JLabel();
        lblDocente = new javax.swing.JLabel();
        lblPrograma = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        lblJornada = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        btnAgregarHorario = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        JComboDocentes = new javax.swing.JComboBox<>();
        cbPrograma = new javax.swing.JComboBox<>();
        btnCrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();
        btnAgregarEstudiantes = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblPeriodo2 = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        comboJornada = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCrearCursos.setText("Crear curso----------------------------------------------------------------------------");
        getContentPane().add(lblCrearCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lblDocente.setText("Id docente:");
        getContentPane().add(lblDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 22));

        lblPrograma.setText("Programa:");
        getContentPane().add(lblPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lblMateria.setText("Materia:");
        getContentPane().add(lblMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        getContentPane().add(txtMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 98, -1));

        lblJornada.setText("Jornada:");
        getContentPane().add(lblJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblPeriodo.setText("Periodo:");
        getContentPane().add(lblPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lblId.setText("Id:");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        btnAgregarHorario.setText("Agregar horarios");
        btnAgregarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 100, -1));
        getContentPane().add(JComboDocentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 100, -1));

        cbPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingenieria", "Ing software", "Ing industrial", "Diseño", "Publicidad", "Administracion", "Negosios" }));
        getContentPane().add(cbPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 100, -1));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Programa", "Materia", "Periodo", "Jornada", "Docente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCursos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 520, 300));

        btnAgregarEstudiantes.setText("Agregar estudiantes");
        btnAgregarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEstudiantesActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 150, -1));

        btnEditar.setText("Editar");
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));
        getContentPane().add(lblPeriodo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 246, 100, 20));

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        comboJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diurna", "Nocturna" }));
        getContentPane().add(comboJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 100, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 471, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondo2.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaUsAdministrativo ventanUA = new VentanaUsAdministrativo(administrativo);
        ventanUA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        try {
            String programa = String.valueOf(cbPrograma.getSelectedItem());
            int id = Integer.parseInt(txtId.getText());
            String materia = txtMateria.getText();
            String jornada = comboJornada.getSelectedItem().toString();
            int periodo = Integer.parseInt(String.valueOf(controlVC.validacionPeriodo()));
            int nombreDocen = JComboDocentes.getSelectedIndex();
            LocalDateTime fechaActual = LocalDateTime.now();
            // here is the notificatio for teacher
            String mensajeNotificacionDocente = "Querido docente " + JComboDocentes.getSelectedItem()
                    + "usted ha\n sido seleccionado para dictar el curso\n de " + materia + " en la jornada " + jornada + " felicitaciones";
            String motivoNotificacionDocenete = "Notificacion asignacion nuevo curso";
            Notificacion notificacionDocente = new Notificacion(fechaActual, mensajeNotificacionDocente, motivoNotificacionDocenete);

            Curso curso = new Curso(controlVC.listaUsuarioDocens().get(nombreDocen), materia, jornada, periodo, programa, id);
            curso.getDocente().getNotificaciones().add(notificacionDocente);
            controlVC.agregarCurso(curso);
            llenarTablaCursos();
        } catch (CursoExistente ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        try {
            int id = Integer.parseInt(txtId.getText());
            controlVC.borrarCursos(id);
            txtId.setText(controlVC.contadorIdCursos());
            llenarTablaCursos();
        } catch (CursoNoRemovido ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            int id = Integer.parseInt(txtId.getText());
            Curso curso = controlVC.buscarCursoPanel(id);
            cbPrograma.setSelectedItem(curso.getPrograma());
            txtMateria.setText(curso.getMateria());
            comboJornada.setSelectedItem(curso.getJornada());
            JComboDocentes.setSelectedItem(curso.getDocente().getNombre());

        } catch (CursoNoEncontrado ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEstudiantesActionPerformed
        try {
            int idCurso = Integer.parseInt(txtId.getText());
            VentanaAgregarEstudiantes ventanaAE = new VentanaAgregarEstudiantes(administrativo, idCurso);
            ventanaAE.setVisible(true);
            this.dispose();
        } catch (IdIncorrecto ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarEstudiantesActionPerformed

    private void btnAgregarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHorarioActionPerformed
        try {
            int idCurso = Integer.parseInt(txtId.getText());
            VentanaAgregarHorarios ventanaAH = new VentanaAgregarHorarios(administrativo, idCurso);
            ventanaAH.setVisible(true);
            this.dispose();
        } catch (IdIncorrecto ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarHorarioActionPerformed

    private void limpiarCampos() {
        cbPrograma.setSelectedItem("Igenieria");
        txtId.setText(controlVC.contadorIdCursos());
        txtMateria.setText("");
        comboJornada.setSelectedItem(null);
        JComboDocentes.setSelectedItem(null);
        resetArrayEstCursos();
    }

    public void llenarComboBoxDocentes() {
        ArrayList<Docente> docens = controlVC.listaUsuarioDocens();
        DefaultComboBoxModel<String> modeloDocentes = new DefaultComboBoxModel<>();
        for (Docente docente : docens) {
            modeloDocentes.addElement(docente.getNombre());
        }
        JComboDocentes.setModel(modeloDocentes);
    }

    public void resetArrayEstCursos() {
        ArrayList<Estudiante> reset = new ArrayList<>();
        estsCurso = reset;
    }

    public void llenarTablaCursos() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Id", "Programa", "Materia", "Periodo", "Jornada", "Docente"}, controlVC.getCursos().size());
        tablaCursos.setModel(modelo);
        TableModel modeloCurso = tablaCursos.getModel();
        for (int i = 0; i < controlVC.getCursos().size(); i++) {
            Curso curso = controlVC.getCursos().get(i);
            modeloCurso.setValueAt(curso.getId(), i, 0);
            modeloCurso.setValueAt(curso.getPrograma(), i, 1);
            modeloCurso.setValueAt(curso.getMateria(), i, 2);
            modeloCurso.setValueAt(curso.getPeriodo(), i, 3);
            modeloCurso.setValueAt(curso.getJornada(), i, 4);
            modeloCurso.setValueAt(curso.getDocente().getNombre(), i, 5);
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboDocentes;
    private javax.swing.JButton btnAgregarEstudiantes;
    private javax.swing.JButton btnAgregarHorario;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbPrograma;
    private javax.swing.JComboBox<String> comboJornada;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCrearCursos;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblJornada;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblPeriodo2;
    private javax.swing.JLabel lblPrograma;
    private javax.swing.JTable tablaCursos;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMateria;
    // End of variables declaration//GEN-END:variables
}
// here is de code for the schedule 1
//        String dia = String.valueOf(jComboDias.getSelectedItem());
//        LocalTime horaInicio = LocalTime.parse(txtHoraInicio.getText());
//        LocalTime horaFinal = LocalTime.parse(txtHoraFinal.getText());
//        Horario horario1 = new Horario(horaInicio, horaFinal, dia);
        // here is the code for the schedule 2
