/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControlVentanaEliminarReserva;
import excepciones.NoTieneReserva;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.AdminLab;
import modelo.Estudiante;

/**
 *
 * @author JORGE
 */
public class VentanaEliminarReserva extends javax.swing.JFrame {

    AdminLab adminlab;
    ControlVentanaEliminarReserva controlVER;

    /**
     * Creates new form VentanaEliminarReserva
     */
    public VentanaEliminarReserva(AdminLab adminlab) {
        initComponents();
        setLocationRelativeTo(this);
        this.adminlab = adminlab;
        controlVER = new ControlVentanaEliminarReserva();
        llenarTablaReservas();
        llenarComboBoxEstudiantesConReserva();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReservaEstudiantes = new javax.swing.JTable();
        cbIdEstudiante = new javax.swing.JComboBox<>();
        btnEliminarReserva = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 351, -1, -1));

        tablaReservaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Estudiante", "Reserva Activa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaReservaEstudiantes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 226));

        getContentPane().add(cbIdEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 244, -1, -1));

        btnEliminarReserva.setText("Eliminar Reserva");
        btnEliminarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarReservaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 244, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 510, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void llenarTablaReservas() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Id", "Estudiante", "Reserva"}, controlVER.usuariosConReserva().size());
        tablaReservaEstudiantes.setModel(modelo);
        TableModel modeloReservas = tablaReservaEstudiantes.getModel();
        for (int i = 0; i < controlVER.usuariosConReserva().size(); i++) {
            Estudiante est = controlVER.usuariosConReserva().get(i);
            modeloReservas.setValueAt(est.getId(), i, 0);
            modeloReservas.setValueAt(est.getNombre(), i, 1);
            modeloReservas.setValueAt(est.isTieneReserva(), i, 2);
        }
    }

    public void llenarComboBoxEstudiantesConReserva() {
        ArrayList<Estudiante> estConReserva = controlVER.usuariosConReserva();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Estudiante est : estConReserva) {
            model.addElement(String.valueOf(est.getId()));
        }
        cbIdEstudiante.setModel(model);
    }


    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VentanaGestionarReservaAdminLab ventanaGRL = new VentanaGestionarReservaAdminLab(adminlab);
        ventanaGRL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEliminarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarReservaActionPerformed
        // TODO add your handling code here:
        try{
        int idEstudiante = Integer.parseInt(String.valueOf(cbIdEstudiante.getSelectedItem()));
        controlVER.eliminarReserva(idEstudiante);
        llenarTablaReservas();
        llenarComboBoxEstudiantesConReserva();
        }catch(NoTieneReserva ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarReservaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarReserva;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbIdEstudiante;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTable tablaReservaEstudiantes;
    // End of variables declaration//GEN-END:variables
}
