/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControlVentanaAgregarEstudiante;
import excepciones.EstudianteNoEliminado;
import excepciones.EstudianteNoInscrito;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Administrativo;
import modelo.Curso;
import modelo.Estudiante;

/**
 *
 * @author JORGE
 */
public class VentanaAgregarEstudiantes extends javax.swing.JFrame {

    ControlVentanaAgregarEstudiante controlVAE;
    Administrativo administrativo;
    int idCurso;
    Curso curso;

    /**
     * Creates new form VentanaAgregarEstudiantes
     */
    public VentanaAgregarEstudiantes(Administrativo administrativo, int idCurso) {
        initComponents();
        setLocationRelativeTo(this);
        this.administrativo = administrativo;
        controlVAE = new ControlVentanaAgregarEstudiante();
        this.idCurso = idCurso;
        this.curso = controlVAE.conseguirCurso(idCurso);
        lblCurso.setText("Curso № " + curso.getId());
        lblDocenteCurso.setText(curso.getDocente().getNombre());
        llenarComboBoxEstudiante();
        llenarTablaEstudiante();
        if (curso.getHorarios().isEmpty()) {
            btnInscribirEstudiante.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboEstudiantes = new javax.swing.JComboBox<>();
        lblIdEstudiantes = new javax.swing.JLabel();
        btnInscribirEstudiante = new javax.swing.JButton();
        btnEliminarEstudiante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        lblCurso = new javax.swing.JLabel();
        lblDocenteCurso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIdEstudiantes.setText("Id estudiante:");

        btnInscribirEstudiante.setText("Inscribir");
        btnInscribirEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirEstudianteActionPerformed(evt);
            }
        });

        btnEliminarEstudiante.setText("Eliminar");
        btnEliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEstudianteActionPerformed(evt);
            }
        });

        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Id", "Programa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEstudiantes);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblCurso.setText("Curso №");

        lblDocenteCurso.setText("Docente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIdEstudiantes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnInscribirEstudiante)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEliminarEstudiante))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDocenteCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(lblDocenteCurso))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdEstudiantes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscribirEstudiante)
                    .addComponent(btnEliminarEstudiante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscribirEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirEstudianteActionPerformed
        try {
            int indexE = jComboEstudiantes.getSelectedIndex();
            if (controlVAE.validarHorariosEstudiante(indexE, idCurso)) {
                controlVAE.inscribirEstudiante(indexE, curso.getId());
                llenarTablaEstudiante();
            } else {
                JOptionPane.showMessageDialog(null, "Imposible inscribir \n se crusan los horarios");
            }
        } catch (EstudianteNoInscrito ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnInscribirEstudianteActionPerformed

    private void btnEliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstudianteActionPerformed
        try {
            int indexE = jComboEstudiantes.getSelectedIndex();
            controlVAE.EliminarEstudiante(indexE, curso.getId());
            llenarTablaEstudiante();
        } catch (EstudianteNoEliminado ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarEstudianteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaCursos ventanaC = new VentanaCursos(administrativo);
        ventanaC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    public void llenarTablaEstudiante() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Nombre", "Id", "Programa"}, curso.getEstudiantes().size());
        tablaEstudiantes.setModel(modelo);
        TableModel modeloEstudiante = tablaEstudiantes.getModel();
        for (int i = 0; i < curso.getEstudiantes().size(); i++) {
            Estudiante estudiante = curso.getEstudiantes().get(i);
            modeloEstudiante.setValueAt(estudiante.getNombre(), i, 0);
            modeloEstudiante.setValueAt(estudiante.getId(), i, 1);
            modeloEstudiante.setValueAt(estudiante.getPrograma(), i, 2);
        }
    }

    public void llenarComboBoxEstudiante() {
        ArrayList<Estudiante> ests = controlVAE.listaUsuarioEsts();
        DefaultComboBoxModel<String> modeloEsts = new DefaultComboBoxModel<>();
        for (Estudiante estudiante : ests) {
            modeloEsts.addElement(estudiante.getNombre());
        }
        jComboEstudiantes.setModel(modeloEsts);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarEstudiante;
    private javax.swing.JButton btnInscribirEstudiante;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> jComboEstudiantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDocenteCurso;
    private javax.swing.JLabel lblIdEstudiantes;
    private javax.swing.JTable tablaEstudiantes;
    // End of variables declaration//GEN-END:variables
}
