/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControlVentanaPrestamos;
import excepciones.PrestamoNoRealizado;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.AdminLab;
import modelo.Estudiante;
import modelo.Laboratorio;
import modelo.Prestamo;
import modelo.Puesto;

/**
 *
 * @author JORGE
 */
public class VentanaPrestamos extends javax.swing.JFrame {

    AdminLab adminLab;
    ControlVentanaPrestamos controlVP;

    /**
     * Creates new form VentanaPrestamos
     */
    public VentanaPrestamos(AdminLab adminLab) {
        initComponents();
        setLocationRelativeTo(this);
        this.adminLab = adminLab;
        controlVP = new ControlVentanaPrestamos();
        cbLabs.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLabsActionPerformed(evt);
            }
        });
        llenarComboEstudiantes();
        llenarCombolabs();
        cbPuestos.setSelectedItem(null);
        cbLabs.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbEstudiantes = new javax.swing.JComboBox<>();
        lblEstudiantes = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JTextField();
        txtHoraFinal = new javax.swing.JTextField();
        lblHoraInicio = new javax.swing.JLabel();
        lblHoraFinal = new javax.swing.JLabel();
        btnGenerarPrestamo = new javax.swing.JButton();
        lblIdLaboratorio = new javax.swing.JLabel();
        lblPuestos = new javax.swing.JLabel();
        cbPuestos = new javax.swing.JComboBox<>();
        cbLabs = new javax.swing.JComboBox<>();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 351, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Prestamos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 6, 87, -1));

        getContentPane().add(cbEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 100, -1));

        lblEstudiantes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstudiantes.setText("Estudiantes:");
        getContentPane().add(lblEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));
        getContentPane().add(txtHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 100, -1));
        getContentPane().add(txtHoraFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 100, -1));

        lblHoraInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHoraInicio.setText("Hora inicio:");
        getContentPane().add(lblHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        lblHoraFinal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHoraFinal.setText("Hora final:");
        getContentPane().add(lblHoraFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        btnGenerarPrestamo.setText("Generar prestamo");
        btnGenerarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPrestamoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 133, -1));

        lblIdLaboratorio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdLaboratorio.setText("IdLaboratorio:");
        getContentPane().add(lblIdLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, 20));

        lblPuestos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPuestos.setText("Puesto:");
        getContentPane().add(lblPuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        getContentPane().add(cbPuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 100, -1));

        getContentPane().add(cbLabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 100, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondo.png"))); // NOI18N
        lblFondo.setText("jLabel2");
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 500, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void llenarComboEstudiantes() {
        ArrayList<Estudiante> ests = controlVP.listaUsuarioEsts();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Estudiante est : ests) {
            model.addElement(est.getNombre());
        }
        cbEstudiantes.setModel(model);
    }

    private void cbLabsActionPerformed(java.awt.event.ActionEvent evt) {
        if (cbLabs.getSelectedItem() != null) {
            int idLaboratorio = Integer.parseInt(String.valueOf(cbLabs.getSelectedIndex()));
            llenarComboBoxPuestos(idLaboratorio);
        }
    }

    public void llenarCombolabs() {
        ArrayList<Laboratorio> labs = controlVP.getLabs();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Laboratorio lab : labs) {
            model.addElement(String.valueOf(lab.getIdLaboratorio()));
        }
        cbLabs.setModel(model);
    }

    public void llenarComboBoxPuestos(int idLaboratorio) {
        DefaultComboBoxModel<String> modelPuesto = new DefaultComboBoxModel<>();
        for (Puesto puesto : controlVP.getLabs().get(idLaboratorio).getPuestos()) {
            modelPuesto.addElement(String.valueOf(puesto.getIdPuesto()));
        }
        cbPuestos.setModel(modelPuesto);
    }
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaUsAdminLab ventanaUAL = new VentanaUsAdminLab(adminLab);
        ventanaUAL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGenerarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPrestamoActionPerformed
        // TODO add your handling code here:
        try {
            int indexEstudiante = cbEstudiantes.getSelectedIndex();
            Estudiante estudiante = controlVP.conseguirEstudiante(indexEstudiante);
            int idLaboratorio = Integer.parseInt(String.valueOf(cbLabs.getSelectedItem()));
            int idPuesto = Integer.parseInt(String.valueOf(cbPuestos.getSelectedItem()));
            LocalTime horaInicio = LocalTime.parse(txtHoraInicio.getText());
            LocalTime horaFinal = LocalTime.parse(txtHoraFinal.getText());
            Duration duration = Duration.between(horaInicio, horaFinal);
            Prestamo prestamo = new Prestamo(estudiante, idLaboratorio, LocalDate.MIN, horaInicio, horaFinal);
            prestamo.setDiaReserva(LocalDate.now());
            if (!estudiante.isTienePrestamo()) {
                if (duration.toMinutes() < 61) {
                    controlVP.generarPrestamo(prestamo, estudiante.getId(), idPuesto);
                } else {
                    JOptionPane.showMessageDialog(null, "EL tiempo no puede exeder una hora");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El estudiante tiene presetamo");
            }
        } catch (PrestamoNoRealizado ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnGenerarPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarPrestamo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbEstudiantes;
    private javax.swing.JComboBox<String> cbLabs;
    private javax.swing.JComboBox<String> cbPuestos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEstudiantes;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHoraFinal;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblIdLaboratorio;
    private javax.swing.JLabel lblPuestos;
    private javax.swing.JTextField txtHoraFinal;
    private javax.swing.JTextField txtHoraInicio;
    // End of variables declaration//GEN-END:variables
}
