/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControlGestionCursos;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Curso;
import modelo.Nota;

/**
 *
 * @author JORGE
 */
public class GestionCursos extends javax.swing.JFrame {

    ArrayList<Curso> cursos;
    ArrayList<Nota> Notas;
    ControlGestionCursos controlG;

    /**
     * Creates new form GestionCursos
     */
    public GestionCursos(ArrayList<Curso> cursos, ControlGestionCursos controlG) {
        initComponents();
        setLocationRelativeTo(this);
        this.controlG = controlG;
        this.cursos = cursos;
        llenarTabla();
        llenarComboBox();
        Notas = new ArrayList<>();
        configuracionNotas();
        checkNota3.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                if (checkNota3.isSelected()) {
                    habilitarCamposNotas3();
                } else {
                    deshabilitarCamposNotas3();
                }
            }
        });
        checkNota4.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                if (checkNota4.isSelected()) {
                    habilitarCamposNotas4();
                } else {
                    deshabilitarCamposNotas4();
                }
            }
        });
        checkNota5.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                if (checkNota5.isSelected()) {
                    habilitarCamposNotas5();
                } else {
                    deshabilitarCamposNotas5();
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCursosAsignados = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        lblIdCurso = new javax.swing.JLabel();
        cbCursosGestionNotas = new javax.swing.JComboBox<>();
        lblNota1 = new javax.swing.JLabel();
        lblNota2 = new javax.swing.JLabel();
        lblNota3 = new javax.swing.JLabel();
        lblNota4 = new javax.swing.JLabel();
        lblNota5 = new javax.swing.JLabel();
        lblRazonNota = new javax.swing.JLabel();
        lblPorcentage = new javax.swing.JLabel();
        txtRazonNota1 = new javax.swing.JTextField();
        txtRazonNota2 = new javax.swing.JTextField();
        txtRazonNota3 = new javax.swing.JTextField();
        lblNumeroNotas = new javax.swing.JLabel();
        checkNota3 = new javax.swing.JCheckBox();
        txtRazonNota4 = new javax.swing.JTextField();
        checkNota4 = new javax.swing.JCheckBox();
        txtRazonNota5 = new javax.swing.JTextField();
        checkNota5 = new javax.swing.JCheckBox();
        txtPorcentajeNota1 = new javax.swing.JTextField();
        txtPorcentajeNota2 = new javax.swing.JTextField();
        txtPorcentajeNota3 = new javax.swing.JTextField();
        txtPorcentajeNota4 = new javax.swing.JTextField();
        btnVerNota = new javax.swing.JButton();
        txtPorcentajeNota5 = new javax.swing.JTextField();
        btnLimpiarCampos = new javax.swing.JButton();
        btnIngresarNotas = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCursosAsignados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Materia", "Hora inicio", "Hora final", "Programa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCursosAsignados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 199));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 471, -1, -1));

        lblIdCurso.setText("Id:");
        getContentPane().add(lblIdCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 217, -1, -1));

        cbCursosGestionNotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(cbCursosGestionNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        lblNota1.setText("Nota 1:");
        getContentPane().add(lblNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 269, -1, -1));

        lblNota2.setText("Nota 2:");
        getContentPane().add(lblNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 303, -1, -1));

        lblNota3.setText("Nota 3:");
        getContentPane().add(lblNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 337, -1, -1));

        lblNota4.setText("Nota 4:");
        getContentPane().add(lblNota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 371, -1, -1));

        lblNota5.setText("Nota 5:");
        getContentPane().add(lblNota5, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 405, -1, -1));

        lblRazonNota.setText("Razon");
        getContentPane().add(lblRazonNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        lblPorcentage.setText("Porcentaje");
        getContentPane().add(lblPorcentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));
        getContentPane().add(txtRazonNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 266, 80, -1));
        getContentPane().add(txtRazonNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 300, 80, -1));
        getContentPane().add(txtRazonNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 334, 80, -1));

        lblNumeroNotas.setText("# Notas");
        getContentPane().add(lblNumeroNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        checkNota3.setText("N3");
        getContentPane().add(checkNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));
        getContentPane().add(txtRazonNota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 368, 80, -1));

        checkNota4.setText("N4");
        getContentPane().add(checkNota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));
        getContentPane().add(txtRazonNota5, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 402, 80, -1));

        checkNota5.setText("N5");
        getContentPane().add(checkNota5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));
        getContentPane().add(txtPorcentajeNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 266, 80, -1));
        getContentPane().add(txtPorcentajeNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 300, 80, -1));
        getContentPane().add(txtPorcentajeNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 334, 80, -1));
        getContentPane().add(txtPorcentajeNota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 368, 80, -1));

        btnVerNota.setText("Ver notas");
        btnVerNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerNotaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 100, -1));
        getContentPane().add(txtPorcentajeNota5, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 402, 80, -1));

        btnLimpiarCampos.setText("Limpiar Campos");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        btnIngresarNotas.setText("Ingresar notas");
        btnIngresarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarNotasActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 113, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoGestionCursos.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarNotasActionPerformed
        // TODO add your handling code here:
        int idCurso = Integer.parseInt((String) cbCursosGestionNotas.getSelectedItem());

        if (checkNota3.isSelected()) {

            String razon1 = txtRazonNota1.getText();
            float pocentage1 = Float.parseFloat(txtPorcentajeNota1.getText());
            Nota nota1 = new Nota(razon1, pocentage1);

            String razon2 = txtRazonNota2.getText();
            float pocentage2 = Float.parseFloat(txtPorcentajeNota2.getText());
            Nota nota2 = new Nota(razon2, pocentage2);

            String razon3 = txtRazonNota3.getText();
            float pocentage3 = Float.parseFloat(txtPorcentajeNota3.getText());
            Nota nota3 = new Nota(razon3, pocentage3);

            if (nota1.getPorcentage() + nota2.getPorcentage() + nota3.getPorcentage() == 1) {
                ArrayList<Nota> notas = new ArrayList<>();
                notas.add(nota1);
                notas.add(nota2);
                notas.add(nota3);
                boolean aux = controlG.configurarNotas(notas, idCurso);
                if (aux) {
                    JOptionPane.showMessageDialog(null, "Las notas han sido assignadas");
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(null, "Las Notas no se asignaron");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las notas estan mal valoradas");
                limpiarCampos();
            }
        } else if (checkNota4.isSelected()) {
            String razon1 = txtRazonNota1.getText();
            float pocentage1 = Float.parseFloat(txtPorcentajeNota1.getText());
            Nota nota1 = new Nota(razon1, pocentage1);

            String razon2 = txtRazonNota2.getText();
            float pocentage2 = Float.parseFloat(txtPorcentajeNota2.getText());
            Nota nota2 = new Nota(razon2, pocentage2);

            String razon3 = txtRazonNota3.getText();
            float pocentage3 = Float.parseFloat(txtPorcentajeNota3.getText());
            Nota nota3 = new Nota(razon3, pocentage3);

            String razon4 = txtRazonNota4.getText();
            float pocentage4 = Float.parseFloat(txtPorcentajeNota4.getText());
            Nota nota4 = new Nota(razon4, pocentage4);

            if (nota1.getPorcentage() + nota2.getPorcentage() + nota3.getPorcentage() + nota4.getPorcentage() == 1) {
                ArrayList<Nota> notas = new ArrayList<>();
                notas.add(nota1);
                notas.add(nota2);
                notas.add(nota3);
                notas.add(nota4);
                boolean aux = controlG.configurarNotas(notas, idCurso);
                if (aux) {
                    JOptionPane.showMessageDialog(null, "Las notas han sido assignadas");
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(null, "Las Notas no se asignaron");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las notas estan mal valoradas");
                limpiarCampos();
            }
        } else if (checkNota5.isSelected()) {
            String razon1 = txtRazonNota1.getText();
            float pocentage1 = Float.parseFloat(txtPorcentajeNota1.getText());
            Nota nota1 = new Nota(razon1, pocentage1);

            String razon2 = txtRazonNota2.getText();
            float pocentage2 = Float.parseFloat(txtPorcentajeNota2.getText());
            Nota nota2 = new Nota(razon2, pocentage2);

            String razon3 = txtRazonNota3.getText();
            float pocentage3 = Float.parseFloat(txtPorcentajeNota3.getText());
            Nota nota3 = new Nota(razon3, pocentage3);

            String razon4 = txtRazonNota4.getText();
            float pocentage4 = Float.parseFloat(txtPorcentajeNota4.getText());
            Nota nota4 = new Nota(razon4, pocentage4);

            String razon5 = txtRazonNota5.getText();
            float pocentage5 = Float.parseFloat(txtPorcentajeNota5.getText());
            Nota nota5 = new Nota(razon5, pocentage5);

            if (nota1.getPorcentage() + nota2.getPorcentage() + nota3.getPorcentage()
                    + nota4.getPorcentage() + nota5.getPorcentage() == 1) {
                ArrayList<Nota> notas = new ArrayList<>();
                notas.add(nota1);
                notas.add(nota2);
                notas.add(nota3);
                notas.add(nota4);
                notas.add(nota5);
                boolean aux = controlG.configurarNotas(notas, idCurso);
                if (aux) {
                    JOptionPane.showMessageDialog(null, "Las notas han sido assignadas");
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(null, "Las Notas no se asignaron");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las notas estan mal valoradas");
                limpiarCampos();
            }
        }
    }//GEN-LAST:event_btnIngresarNotasActionPerformed

    private void btnVerNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerNotaActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        int idCurso = Integer.parseInt((String) cbCursosGestionNotas.getSelectedItem());
        ArrayList<Nota> notas = controlG.mostrarNotas(idCurso);
        if (notas.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay notas asignadas");
        } else if (notas.size() == 3) {
            txtRazonNota1.setText(notas.get(0).getRazon());
            txtPorcentajeNota1.setText(String.valueOf(notas.get(0).getPorcentage()));

            txtRazonNota2.setText(notas.get(1).getRazon());
            txtPorcentajeNota2.setText(String.valueOf(notas.get(1).getPorcentage()));

            txtRazonNota3.setText(notas.get(2).getRazon());
            txtPorcentajeNota3.setText(String.valueOf(notas.get(2).getPorcentage()));
        } else if (notas.size() == 4) {
            txtRazonNota1.setText(notas.get(0).getRazon());
            txtPorcentajeNota1.setText(String.valueOf(notas.get(0).getPorcentage()));

            txtRazonNota2.setText(notas.get(1).getRazon());
            txtPorcentajeNota2.setText(String.valueOf(notas.get(1).getPorcentage()));

            txtRazonNota3.setText(notas.get(2).getRazon());
            txtPorcentajeNota3.setText(String.valueOf(notas.get(2).getPorcentage()));

            txtRazonNota4.setText(notas.get(3).getRazon());
            txtPorcentajeNota4.setText(String.valueOf(notas.get(3).getPorcentage()));
        } else if (notas.size() == 5) {
            txtRazonNota1.setText(notas.get(0).getRazon());
            txtPorcentajeNota1.setText(String.valueOf(notas.get(0).getPorcentage()));

            txtRazonNota2.setText(notas.get(1).getRazon());
            txtPorcentajeNota2.setText(String.valueOf(notas.get(1).getPorcentage()));

            txtRazonNota3.setText(notas.get(2).getRazon());
            txtPorcentajeNota3.setText(String.valueOf(notas.get(2).getPorcentage()));

            txtRazonNota4.setText(notas.get(3).getRazon());
            txtPorcentajeNota4.setText(String.valueOf(notas.get(3).getPorcentage()));

            txtRazonNota5.setText(notas.get(4).getRazon());
            txtPorcentajeNota5.setText(String.valueOf(notas.get(4).getPorcentage()));
        }

    }//GEN-LAST:event_btnVerNotaActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void llenarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Id", "Materia", "Hora inicio", "Hora final", "Programa"}, cursos.size());
        tablaCursosAsignados.setModel(modelo);
        TableModel modeloCursoA = tablaCursosAsignados.getModel();
        for (int i = 0; i < cursos.size(); i++) {
            Curso curso = cursos.get(i);
            modeloCursoA.setValueAt(curso.getId(), i, 0);
            modeloCursoA.setValueAt(curso.getMaterial(), i, 1);
            modeloCursoA.setValueAt(curso.getHorario().getHoraInicio(), i, 2);
            modeloCursoA.setValueAt(curso.getHorario().getHoraFinal(), i, 3);
            modeloCursoA.setValueAt(curso.getPrograma(), i, 4);
        }
    }

    private void llenarComboBox() {
        DefaultComboBoxModel<String> modeloCurso = new DefaultComboBoxModel<>();
        for (Curso curso : cursos) {
            modeloCurso.addElement(String.valueOf(curso.getId()));
        }
        cbCursosGestionNotas.setModel(modeloCurso);
    }

    private void configuracionNotas() {
        txtRazonNota1.setEnabled(false);
        txtPorcentajeNota1.setEnabled(false);
        txtRazonNota2.setEnabled(false);
        txtPorcentajeNota2.setEnabled(false);
        txtRazonNota3.setEnabled(false);
        txtPorcentajeNota3.setEnabled(false);
        txtRazonNota4.setEnabled(false);
        txtPorcentajeNota4.setEnabled(false);
        txtRazonNota5.setEnabled(false);
        txtPorcentajeNota5.setEnabled(false);
        btnIngresarNotas.setEnabled(true);

    }

    private void habilitarCamposNotas3() {
        txtRazonNota1.setEnabled(true);
        txtPorcentajeNota1.setEnabled(true);
        txtRazonNota2.setEnabled(true);
        txtPorcentajeNota2.setEnabled(true);
        txtRazonNota3.setEnabled(true);
        txtPorcentajeNota3.setEnabled(true);
        checkNota4.setEnabled(false);
        checkNota5.setEnabled(false);
    }

    private void deshabilitarCamposNotas3() {
        txtRazonNota1.setEnabled(false);
        txtPorcentajeNota1.setEnabled(false);
        txtRazonNota2.setEnabled(false);
        txtPorcentajeNota2.setEnabled(false);
        txtRazonNota3.setEnabled(false);
        txtPorcentajeNota3.setEnabled(false);
        checkNota4.setEnabled(true);
        checkNota5.setEnabled(true);
    }

    private void habilitarCamposNotas4() {
        txtRazonNota1.setEnabled(true);
        txtPorcentajeNota1.setEnabled(true);
        txtRazonNota2.setEnabled(true);
        txtPorcentajeNota2.setEnabled(true);
        txtRazonNota3.setEnabled(true);
        txtPorcentajeNota3.setEnabled(true);
        txtRazonNota4.setEnabled(true);
        txtPorcentajeNota4.setEnabled(true);
        checkNota3.setEnabled(false);
        checkNota5.setEnabled(false);
    }

    private void deshabilitarCamposNotas4() {
        txtRazonNota1.setEnabled(false);
        txtPorcentajeNota1.setEnabled(false);
        txtRazonNota2.setEnabled(false);
        txtPorcentajeNota2.setEnabled(false);
        txtRazonNota3.setEnabled(false);
        txtPorcentajeNota3.setEnabled(false);
        txtRazonNota4.setEnabled(false);
        txtPorcentajeNota4.setEnabled(false);
        checkNota3.setEnabled(true);
        checkNota5.setEnabled(true);
    }

    private void habilitarCamposNotas5() {
        txtRazonNota1.setEnabled(true);
        txtPorcentajeNota1.setEnabled(true);
        txtRazonNota2.setEnabled(true);
        txtPorcentajeNota2.setEnabled(true);
        txtRazonNota3.setEnabled(true);
        txtPorcentajeNota3.setEnabled(true);
        txtRazonNota4.setEnabled(true);
        txtPorcentajeNota4.setEnabled(true);
        txtRazonNota5.setEnabled(true);
        txtPorcentajeNota5.setEnabled(true);
        checkNota3.setEnabled(false);
        checkNota4.setEnabled(false);
    }

    private void deshabilitarCamposNotas5() {
        txtRazonNota1.setEnabled(false);
        txtPorcentajeNota1.setEnabled(false);
        txtRazonNota2.setEnabled(false);
        txtPorcentajeNota2.setEnabled(false);
        txtRazonNota3.setEnabled(false);
        txtPorcentajeNota3.setEnabled(false);
        txtRazonNota4.setEnabled(false);
        txtPorcentajeNota4.setEnabled(false);
        txtRazonNota5.setEnabled(false);
        txtPorcentajeNota5.setEnabled(false);
        checkNota3.setEnabled(true);
        checkNota4.setEnabled(true);
    }

    public void limpiarCampos() {
        txtRazonNota1.setText("");
        txtPorcentajeNota1.setText("");
        txtRazonNota2.setText("");
        txtPorcentajeNota2.setText("");
        txtRazonNota3.setText("");
        txtPorcentajeNota3.setText("");
        txtRazonNota4.setText("");
        txtPorcentajeNota4.setText("");
        txtRazonNota5.setText("");
        txtPorcentajeNota5.setText("");

    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarNotas;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerNota;
    private javax.swing.JComboBox<String> cbCursosGestionNotas;
    private javax.swing.JCheckBox checkNota3;
    private javax.swing.JCheckBox checkNota4;
    private javax.swing.JCheckBox checkNota5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIdCurso;
    private javax.swing.JLabel lblNota1;
    private javax.swing.JLabel lblNota2;
    private javax.swing.JLabel lblNota3;
    private javax.swing.JLabel lblNota4;
    private javax.swing.JLabel lblNota5;
    private javax.swing.JLabel lblNumeroNotas;
    private javax.swing.JLabel lblPorcentage;
    private javax.swing.JLabel lblRazonNota;
    private javax.swing.JTable tablaCursosAsignados;
    private javax.swing.JTextField txtPorcentajeNota1;
    private javax.swing.JTextField txtPorcentajeNota2;
    private javax.swing.JTextField txtPorcentajeNota3;
    private javax.swing.JTextField txtPorcentajeNota4;
    private javax.swing.JTextField txtPorcentajeNota5;
    private javax.swing.JTextField txtRazonNota1;
    private javax.swing.JTextField txtRazonNota2;
    private javax.swing.JTextField txtRazonNota3;
    private javax.swing.JTextField txtRazonNota4;
    private javax.swing.JTextField txtRazonNota5;
    // End of variables declaration//GEN-END:variables
}
