/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControlGestionCursos;
import controladores.ControlTablaAdminLab;
import controladores.ControlTablaAdministrativo;
import controladores.ControlTablaDocente;
import controladores.ControlTablaEstudiante;
import controladores.ControlTablaUsuarioDocente;
import controladores.ControlTablaUsuarioEstudiante;
import controladores.ControlVentanaAdminLab;
import controladores.ControlVentanaAdministrativo;
import controladores.ControlVentanaCursos;
import controladores.ControlVentanaDocente;
import controladores.ControlVentanaEstudiante;
import controladores.ControlVentanaLaboratorios;
import controladores.ControladorAdminLab;
import controladores.ControladorAdministrador;
import controladores.ControladorAdministrativo;
import controladores.ControladorDocente;
import controladores.ControladorEstudiante;
import controladores.ControladorPrincipal;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import modelo.AdminLab;
import modelo.Docente;

/**
 *
 * @author JORGE
 */
public class VentanaUsAdminLab extends javax.swing.JFrame {

     ControladorPrincipal controlP;
    ControladorAdministrador controlA;
    ControladorEstudiante controlE;
    ControladorDocente controlD;
    ControladorAdministrativo controlUA;
    ControladorAdminLab controlAL;
    ControlVentanaEstudiante controlVE;
    ControlVentanaDocente controlVD;
    ControlVentanaAdministrativo controlVA;
    ControlVentanaAdminLab controlVAL;
    ControlVentanaCursos controlVC;
    ControlVentanaLaboratorios controlVL;
    ControlTablaEstudiante controlTE;
    ControlTablaDocente controlTD;
    ControlTablaAdministrativo controlTA;
    ControlTablaAdminLab controlTAL;
    ControlTablaUsuarioEstudiante controlTUE;
    ControlTablaUsuarioDocente controlTUD;
    ControlGestionCursos controlGC;
    PanelPrincipal panelP;
    PanelAdministrador panelA;
    PanelIngresarEstudiante panelIE;
    PanelIngresarDocente panelID;
    PanelIngresarAdministrativo panelIA;
    PanelIngresarAdminLab panelIAL;
    VentanaUsEstudiante ventanaE;
    VentanaUsDocente ventanaD;
    VentanaUsAdministrativo ventanaA;
    VentanaCursos ventanaC;
    VentanaLaboratorios ventanaL;

    /**
     * Creates new form VentanaUsuarioAdminLab
     */
    public VentanaUsAdminLab(ControladorPrincipal controlP, ControladorAdministrador controlA,
            ControladorEstudiante controlE, ControladorDocente controlD, ControladorAdministrativo controlUA,
            ControladorAdminLab controlAL, ControlVentanaEstudiante controlVE, ControlVentanaDocente controlVD,
            ControlVentanaAdministrativo controlVA, ControlVentanaAdminLab controlVAL, ControlVentanaCursos controlVC,
            ControlVentanaLaboratorios controlVL, ControlTablaEstudiante controlTE, ControlTablaDocente controlTD,
            ControlTablaAdministrativo controlTA, ControlTablaAdminLab controlTAL, ControlTablaUsuarioEstudiante controlTUE,
            ControlTablaUsuarioDocente controlTUD,ControlGestionCursos controlGC, PanelPrincipal panelP, PanelAdministrador panelA, PanelIngresarEstudiante panelIE,
            PanelIngresarDocente panelID, PanelIngresarAdministrativo panelIA, PanelIngresarAdminLab panelIAL,
            VentanaUsEstudiante ventanaE, VentanaUsDocente ventanaD, VentanaUsAdministrativo ventanaA,
            VentanaCursos ventanaC, VentanaLaboratorios ventanaL) {
        initComponents();
        setLocationRelativeTo(this);
      this.controlP = controlP;
        this.controlA = controlA;
        this.controlE = controlE;
        this.controlD = controlD;
        this.controlUA = controlUA;
        this.controlAL = controlAL;
        this.controlVE = controlVE;
        this.controlVD = controlVD;
        this.controlVA = controlVA;
        this.controlVAL = controlVAL;
        this.controlVC = controlVC;
        this.controlVL = controlVL;
        this.controlTE = controlTE;
        this.controlTD = controlTD;
        this.controlTA = controlTA;
        this.controlTAL = controlTAL;
        this.controlTUE = controlTUE;
        this.controlTUD = controlTUD;
        this.controlGC = controlGC;
        this.panelP = panelP;
        this.panelA = panelA;
        this.panelIE = panelIE;
        this.panelID = panelID;
        this.panelIA = panelIA;
        this.panelIAL = panelIAL;
        this.ventanaE = ventanaE;
        this.ventanaD = ventanaD;
        this.ventanaA = ventanaA;
        this.ventanaC = ventanaC;
        this.ventanaL = ventanaL;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSecion = new javax.swing.JButton();
        lblBirthDateAdminLabs = new javax.swing.JLabel();
        lblNombreAdminLabs = new javax.swing.JLabel();
        lblAdminLabs = new javax.swing.JLabel();
        LblBirthDate = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblEdadAdminLab = new javax.swing.JLabel();
        lblInformacionDeUsuario = new javax.swing.JLabel();
        lblLineaLimite1 = new javax.swing.JLabel();
        btnCrearCursos = new javax.swing.JButton();
        btnCrearLab = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSecion.setText("Cerrar secion");
        btnCerrarSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSecionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 471, -1, -1));
        getContentPane().add(lblBirthDateAdminLabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 54, 121, 20));
        getContentPane().add(lblNombreAdminLabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 28, 121, 20));

        lblAdminLabs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAdminLabs.setText("Administrador labs:");
        getContentPane().add(lblAdminLabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, -1, -1));

        LblBirthDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblBirthDate.setText("Año de nacimiento:");
        getContentPane().add(LblBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 54, -1, -1));

        lblEdad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEdad.setText("Edad:");
        getContentPane().add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        getContentPane().add(lblEdadAdminLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 80, 121, 20));

        lblInformacionDeUsuario.setText("Informacion de usuario----------------------------------------------------------------");
        getContentPane().add(lblInformacionDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        lblLineaLimite1.setText("____________________________________________________________________________________");
        getContentPane().add(lblLineaLimite1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 430, -1));

        btnCrearCursos.setText("Crear curso");
        btnCrearCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCursosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 251, -1));

        btnCrearLab.setText("Crear lab");
        btnCrearLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearLabActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 251, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondo2.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 460, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSecionActionPerformed
        // TODO add your handling code here:
        PanelPrincipal panelP = new PanelPrincipal(controlP, controlA, controlE, controlD, controlUA, controlAL, controlVE, controlVD, controlVA, controlVAL, controlVC, controlVL, controlTE, controlTD, controlTA, controlTAL, controlTUE, controlTUD, controlGC, panelA, panelIE, panelID, panelIA, panelIAL, ventanaE, ventanaD, ventanaA, this, ventanaC, ventanaL);
        panelP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSecionActionPerformed

    private void btnCrearCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCursosActionPerformed
        // TODO add your handling code here:
        VentanaCursos ventanaC = new VentanaCursos(controlP, controlA, controlE, controlD, controlUA, controlAL, controlVE, controlVD, controlVA, controlVAL, controlVC, controlVL, controlTE, controlTD, controlTA, controlTAL, controlTUE, controlTUD, controlGC, panelP, panelA, panelIE, panelID, panelIA, panelIAL, ventanaE, ventanaD, ventanaA, this, ventanaL);
        ventanaC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearCursosActionPerformed

    private void btnCrearLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearLabActionPerformed
        // TODO add your handling code here:
        VentanaLaboratorios ventanaL = new VentanaLaboratorios(controlP, controlA, controlE, controlD, controlUA, controlAL, controlVE, controlVD, controlVA, controlVAL, controlVC, controlVL, controlTE, controlTD, controlTA, controlTAL, controlTUE, controlTUD, panelA, panelIE, panelID, panelIA, panelIAL, ventanaE, ventanaD, ventanaA, this, ventanaC);
        ventanaL.setVisible(true);
        setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearLabActionPerformed
 public void informacionAdminLab(AdminLab adminLab) {
        AdminLab aux = adminLab;
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(aux.getBirthDate());
        lblNombreAdminLabs.setText(aux.getNombre());
        lblBirthDateAdminLabs.setText(String.valueOf(calendar.get(Calendar.YEAR)));
        lblEdadAdminLab.setText(String.valueOf(2024-calendar.get(Calendar.YEAR)));
    }
    
 /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblBirthDate;
    private javax.swing.JButton btnCerrarSecion;
    private javax.swing.JButton btnCrearCursos;
    private javax.swing.JButton btnCrearLab;
    private javax.swing.JLabel lblAdminLabs;
    private javax.swing.JLabel lblBirthDateAdminLabs;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEdadAdminLab;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblInformacionDeUsuario;
    private javax.swing.JLabel lblLineaLimite1;
    private javax.swing.JLabel lblNombreAdminLabs;
    // End of variables declaration//GEN-END:variables
}
